name: "リリース作業"
description: "バージョンアップ用のIssueを作成してください。"
title: "vX.X.X"
labels: ["new"]
type: "Task"

body:
  - type: textarea
    id: release_branch_limit
    attributes:
      label: "リリースブランチ"

  - type: textarea
    id: update_limit
    attributes:
      label: "アップデート"

  - type: textarea
    id: prs
    attributes:
      label: 対象PR
