import type { WebtestQuestionInsert } from "./types";

type SampleWebtestQuestion = Omit<WebtestQuestionInsert, "user_id">;

export const SAMPLE_WEBTEST_QUESTIONS: SampleWebtestQuestion[] = [
  {
    title: "SPI計数: 割引後の価格",
    body: "定価2,400円の商品を25%引きで購入した。支払った金額はいくらか。",
    test_type: "SPI",
    category: "計数",
    format: "計算",
    difficulty: "易",
    time_limit: 60,
    choices: ["1,600円", "1,700円", "1,800円", "1,900円"],
    answer: "1,800円",
    explanation: "25%引きは定価の75%を支払うということ。2,400 x 0.75 = 1,800。",
  },
  {
    title: "SPI計数: 速さと時間",
    body: "時速48kmで走る車が20分間進む距離は何kmか。",
    test_type: "SPI",
    category: "計数",
    format: "計算",
    difficulty: "易",
    time_limit: 60,
    choices: ["12km", "14km", "16km", "18km"],
    answer: "16km",
    explanation: "20分は1/3時間。48 x 1/3 = 16km。",
  },
  {
    title: "SPI計数: 損益算",
    body: "ある商品を原価800円で仕入れ、25%の利益を見込んで定価をつけた。定価はいくらか。",
    test_type: "SPI",
    category: "計数",
    format: "計算",
    difficulty: "普通",
    time_limit: 75,
    choices: ["950円", "1,000円", "1,050円", "1,100円"],
    answer: "1,000円",
    explanation: "原価800円の25%は200円。800 + 200 = 1,000円。",
  },
  {
    title: "SPI計数: 構成比",
    body: "あるクラス40人のうち、男子は18人である。女子の割合は何%か。",
    test_type: "SPI",
    category: "計数",
    format: "割合",
    difficulty: "易",
    time_limit: 60,
    choices: ["45%", "50%", "55%", "60%"],
    answer: "55%",
    explanation: "女子は40 - 18 = 22人。22 / 40 = 0.55なので55%。",
  },
  {
    title: "SPI言語: 二語関係",
    body: "「医師 : 病院」と同じ関係になる組み合わせを選べ。",
    test_type: "SPI",
    category: "言語",
    format: "二語関係",
    difficulty: "易",
    time_limit: 45,
    choices: ["教師 : 学校", "机 : 椅子", "山 : 川", "本 : 読書"],
    answer: "教師 : 学校",
    explanation: "前者が働く場所が後者。医師は病院で働き、教師は学校で働く。",
  },
  {
    title: "SPI言語: 反意語",
    body: "「慎重」の反対の意味に最も近い語を選べ。",
    test_type: "SPI",
    category: "言語",
    format: "語句",
    difficulty: "易",
    time_limit: 45,
    choices: ["軽率", "緻密", "冷静", "堅実"],
    answer: "軽率",
    explanation: "慎重は注意深いこと。反対は軽はずみな「軽率」。",
  },
  {
    title: "SPI言語: 空欄補充",
    body: "次の文の空欄に入る語として最も適切なものを選べ。\n\n彼は失敗を恐れず、常に新しい方法を（　）する姿勢を持っている。",
    test_type: "SPI",
    category: "言語",
    format: "空欄補充",
    difficulty: "普通",
    time_limit: 60,
    choices: ["模索", "妥協", "放置", "撤回"],
    answer: "模索",
    explanation: "新しい方法を探し求める文脈なので「模索」が適切。",
  },
  {
    title: "SPI言語: 長文要旨",
    body: "次の文章の要旨として最も適切なものを選べ。\n\n近年、仕事では専門知識だけでなく、異なる立場の人と協力する力が重視されている。複雑な課題は一人の知識だけでは解決しにくく、多様な視点を組み合わせることでより良い解決策が生まれるからである。",
    test_type: "SPI",
    category: "言語",
    format: "読解",
    difficulty: "普通",
    time_limit: 90,
    choices: [
      "専門知識は仕事で不要になっている",
      "複雑な課題には協働と多様な視点が重要である",
      "一人で考える方が効率的である",
      "仕事では立場の違いを避けるべきである",
    ],
    answer: "複雑な課題には協働と多様な視点が重要である",
    explanation: "本文は、専門知識に加えて協力する力や多様な視点が重要だと述べている。",
  },
  {
    title: "SPI計数: 仕事算",
    body: "Aさんが1人で行うと12日、Bさんが1人で行うと6日かかる仕事がある。2人で一緒に行うと何日で終わるか。",
    test_type: "SPI",
    category: "計数",
    format: "仕事算",
    difficulty: "普通",
    time_limit: 90,
    choices: ["3日", "4日", "5日", "6日"],
    answer: "4日",
    explanation: "1日あたりAは1/12、Bは1/6進める。合計は1/12 + 2/12 = 3/12 = 1/4なので4日。",
  },
  {
    title: "SPI言語: 熟語の意味",
    body: "「杞憂」の意味として最も適切なものを選べ。",
    test_type: "SPI",
    category: "言語",
    format: "語句",
    difficulty: "普通",
    time_limit: 45,
    choices: ["無用な心配", "深い感謝", "急な予定変更", "確実な予測"],
    answer: "無用な心配",
    explanation: "杞憂は、心配する必要のないことをあれこれ心配すること。",
  },
  {
    title: "玉手箱: 表の読み取り",
    body: "A店の売上は1月が120万円、2月が150万円、3月が180万円だった。1月から3月にかけて売上は何%増加したか。",
    test_type: "玉手箱",
    category: "計数",
    format: "表の読み取り",
    difficulty: "普通",
    time_limit: 75,
    choices: ["30%", "40%", "50%", "60%"],
    answer: "50%",
    explanation: "増加額は180 - 120 = 60万円。60 / 120 = 0.5なので50%。",
  },
  {
    title: "玉手箱: 四則逆算",
    body: "□に入る数を求めよ。\n\n□ x 6 - 18 = 42",
    test_type: "玉手箱",
    category: "計数",
    format: "四則逆算",
    difficulty: "易",
    time_limit: 45,
    choices: ["8", "9", "10", "11"],
    answer: "10",
    explanation: "□ x 6 = 60 なので、□ = 10。",
  },
  {
    title: "玉手箱: 図表読取 伸び率比較",
    body: "A商品の売上は前年80万円、今年100万円。B商品の売上は前年150万円、今年180万円。売上の伸び率が高い商品はどちらか。",
    test_type: "玉手箱",
    category: "計数",
    format: "図表読取",
    difficulty: "普通",
    time_limit: 75,
    choices: ["A商品", "B商品", "同じ", "判断できない"],
    answer: "A商品",
    explanation: "Aは20/80 = 25%増、Bは30/150 = 20%増。伸び率はAの方が高い。",
  },
  {
    title: "玉手箱: 四則逆算 分数",
    body: "□に入る数を求めよ。\n\n□ / 4 + 7 = 19",
    test_type: "玉手箱",
    category: "計数",
    format: "四則逆算",
    difficulty: "易",
    time_limit: 45,
    choices: ["36", "40", "44", "48"],
    answer: "48",
    explanation: "□ / 4 = 12 なので、□ = 48。",
  },
  {
    title: "玉手箱: 計数 平均",
    body: "5人のテスト平均点は72点だった。そこに80点の1人が加わると、6人の平均点は何点になるか。",
    test_type: "玉手箱",
    category: "計数",
    format: "計算",
    difficulty: "普通",
    time_limit: 60,
    choices: ["72点", "73点", "74点", "75点"],
    answer: "73点",
    explanation: "5人の合計は72 x 5 = 360点。80点を加えて440点。440 / 6 = 73.33...なので選択肢では73点。",
  },
  {
    title: "玉手箱: 言語 趣旨把握",
    body: "次の文章の趣旨として最も適切なものを選べ。\n\n業務効率化は単に作業時間を短くすることではない。不要な作業を見直し、必要な判断に時間を使えるようにすることで、成果の質を高めることが重要である。",
    test_type: "玉手箱",
    category: "言語",
    format: "趣旨把握",
    difficulty: "普通",
    time_limit: 75,
    choices: [
      "効率化では作業時間だけを短くすればよい",
      "不要な作業を見直し、重要な判断に時間を使うべきである",
      "判断に時間を使うことは効率化に反する",
      "成果の質より作業量が重要である",
    ],
    answer: "不要な作業を見直し、重要な判断に時間を使うべきである",
    explanation: "本文は、効率化の目的を時間短縮だけでなく成果の質向上に置いている。",
  },
  {
    title: "玉手箱: 英語 語彙",
    body: "次の英文の空欄に入る語として最も適切なものを選べ。\n\nThe new system will ___ the time required to process applications.",
    test_type: "玉手箱",
    category: "英語",
    format: "語彙",
    difficulty: "普通",
    time_limit: 60,
    choices: ["reduce", "refuse", "replace", "remain"],
    answer: "reduce",
    explanation: "文意は「申請処理に必要な時間を減らす」。reduce が適切。",
  },
  {
    title: "玉手箱: 英語 読解",
    body: "Read the sentence and choose the best summary.\n\nMany companies now allow employees to work remotely because it can reduce commuting time and improve flexibility.",
    test_type: "玉手箱",
    category: "英語",
    format: "読解",
    difficulty: "普通",
    time_limit: 75,
    choices: [
      "Remote work can improve flexibility and reduce commuting time.",
      "Companies prohibit remote work to increase commuting time.",
      "Employees must work only in offices.",
      "Flexibility has no relation to work style.",
    ],
    answer: "Remote work can improve flexibility and reduce commuting time.",
    explanation: "本文は、リモート勤務が通勤時間削減と柔軟性向上につながると述べている。",
  },
  {
    title: "玉手箱: 計数 割合差",
    body: "ある商品の不良品率は全体の4%で、不良品は12個だった。検査した商品は全部で何個か。",
    test_type: "玉手箱",
    category: "計数",
    format: "割合",
    difficulty: "普通",
    time_limit: 60,
    choices: ["200個", "250個", "300個", "350個"],
    answer: "300個",
    explanation: "全体をx個とすると0.04x = 12。x = 300。",
  },
  {
    title: "玉手箱: 四則逆算 小数",
    body: "□に入る数を求めよ。\n\n□ x 0.8 = 64",
    test_type: "玉手箱",
    category: "計数",
    format: "四則逆算",
    difficulty: "易",
    time_limit: 45,
    choices: ["72", "80", "88", "96"],
    answer: "80",
    explanation: "□ = 64 / 0.8 = 80。",
  },
  {
    title: "TG-WEB: 推論",
    body: "A、B、Cの3人がいる。AはBより背が高い。CはAより背が低い。このとき必ず正しいことを選べ。",
    test_type: "TG-WEB",
    category: "非言語",
    format: "推論",
    difficulty: "普通",
    time_limit: 75,
    choices: [
      "BはCより背が高い",
      "CはBより背が高い",
      "AはCより背が高い",
      "BはAより背が高い",
    ],
    answer: "AはCより背が高い",
    explanation: "条件に「CはAより背が低い」とあるため、AはCより背が高いことが必ず成り立つ。",
  },
  {
    title: "TG-WEB: 暗号",
    body: "ある規則で「CAT」を「DBU」と表す。同じ規則で「DOG」を表すとどれか。",
    test_type: "TG-WEB",
    category: "非言語",
    format: "暗号",
    difficulty: "普通",
    time_limit: 60,
    choices: ["EPH", "CNE", "FQI", "EPG"],
    answer: "EPH",
    explanation: "各文字をアルファベット順で1つ後ろにずらす。D->E、O->P、G->H。",
  },
  {
    title: "TG-WEB: 命題 三段論法",
    body: "次の条件がある。\n\nすべての営業職は顧客対応を行う。顧客対応を行う人の一部は資料作成も行う。\n\n必ず正しいことを選べ。",
    test_type: "TG-WEB",
    category: "非言語",
    format: "命題",
    difficulty: "普通",
    time_limit: 90,
    choices: [
      "すべての営業職は資料作成を行う",
      "顧客対応を行う人は全員営業職である",
      "営業職は顧客対応を行う",
      "資料作成を行う人は全員営業職である",
    ],
    answer: "営業職は顧客対応を行う",
    explanation: "1つ目の条件から、営業職なら必ず顧客対応を行うことがいえる。",
  },
  {
    title: "TG-WEB: 展開図",
    body: "立方体の展開図で、向かい合う面の数字の和がすべて7になる。1の向かいの面にある数字は何か。",
    test_type: "TG-WEB",
    category: "非言語",
    format: "図形",
    difficulty: "易",
    time_limit: 60,
    choices: ["2", "3", "5", "6"],
    answer: "6",
    explanation: "向かい合う面の和が7なので、1の向かいは6。",
  },
  {
    title: "TG-WEB: 順序関係",
    body: "A、B、C、Dが横一列に並ぶ。AはBの左、CはBの右、DはAの右にいる。必ずいえることを選べ。",
    test_type: "TG-WEB",
    category: "非言語",
    format: "推論",
    difficulty: "普通",
    time_limit: 90,
    choices: [
      "AはCより左にいる",
      "DはBより右にいる",
      "CはDより左にいる",
      "BはAより左にいる",
    ],
    answer: "AはCより左にいる",
    explanation: "AはBの左、CはBの右なので、Aは必ずCより左にいる。",
  },
  {
    title: "TG-WEB: 数列",
    body: "次の数列の□に入る数を選べ。\n\n3, 6, 12, 24, □",
    test_type: "TG-WEB",
    category: "非言語",
    format: "数列",
    difficulty: "易",
    time_limit: 45,
    choices: ["30", "36", "42", "48"],
    answer: "48",
    explanation: "前の数を2倍している。24 x 2 = 48。",
  },
  {
    title: "TG-WEB: 図形規則",
    body: "丸、三角、四角、丸、三角、四角、丸、□ と並んでいる。□に入る図形はどれか。",
    test_type: "TG-WEB",
    category: "非言語",
    format: "規則性",
    difficulty: "易",
    time_limit: 45,
    choices: ["丸", "三角", "四角", "星"],
    answer: "三角",
    explanation: "丸、三角、四角の3つが繰り返されている。",
  },
  {
    title: "TG-WEB: 条件整理",
    body: "会議室A、B、Cを予約する。営業部は会議室Aを使わない。開発部は会議室Bを使う。人事部は残った会議室を使う。営業部が使う会議室はどれか。",
    test_type: "TG-WEB",
    category: "非言語",
    format: "推論",
    difficulty: "普通",
    time_limit: 90,
    choices: ["会議室A", "会議室B", "会議室C", "判断できない"],
    answer: "会議室C",
    explanation: "開発部がBを使い、営業部はAを使わないため、営業部はC。人事部はAを使う。",
  },
  {
    title: "TG-WEB: 集合",
    body: "30人のうち、英語が得意な人は18人、数学が得意な人は14人、両方得意な人は6人だった。少なくともどちらか一方が得意な人は何人か。",
    test_type: "TG-WEB",
    category: "非言語",
    format: "集合",
    difficulty: "普通",
    time_limit: 90,
    choices: ["20人", "24人", "26人", "28人"],
    answer: "26人",
    explanation: "18 + 14 - 6 = 26人。",
  },
  {
    title: "TG-WEB: 暗号 逆順",
    body: "ある規則で「ABCD」を「DCBA」と表す。同じ規則で「WORK」を表すとどれか。",
    test_type: "TG-WEB",
    category: "非言語",
    format: "暗号",
    difficulty: "易",
    time_limit: 45,
    choices: ["KROW", "WROK", "ROKW", "KWOR"],
    answer: "KROW",
    explanation: "文字の順番を逆にしている。WORKを逆順にするとKROW。",
  },
];
